// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Data.JsonValidation")>]
[<assembly: AssemblyProductAttribute("FSharp.Data.JsonValidation")>]
[<assembly: AssemblyDescriptionAttribute("Validate your JSON values using data structures. Inspired by [joi](https://github.com/hapijs/joi).")>]
[<assembly: AssemblyVersionAttribute("0.99.1")>]
[<assembly: AssemblyFileVersionAttribute("0.99.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.JsonValidation"
    let [<Literal>] AssemblyProduct = "FSharp.Data.JsonValidation"
    let [<Literal>] AssemblyDescription = "Validate your JSON values using data structures. Inspired by [joi](https://github.com/hapijs/joi)."
    let [<Literal>] AssemblyVersion = "0.99.1"
    let [<Literal>] AssemblyFileVersion = "0.99.1"
    let [<Literal>] AssemblyConfiguration = "Release"
